kinect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kinect_core.urls'))
]

kinect_core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.login_user, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('home/', views.home, name='home'),
    path('create/', views.createPhoto, name='create'),
    path('profile/<int:user_id>', views.profile_view, name='profile'),
    path('follow/<int:user_id>', views.follow_user, name='follow'),
    path('unfollow/<int:user_id>', views.unfollow_user, name='unfollow'),
    path('search/', views.search, name='search'),
    path('logout/', views.logout_user, name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kinect_core/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth import get_user_model
User = get_user_model()
# Create your models here.

class Photo(models.Model):
    description = models.TextField()
    photo_path = models.ImageField(upload_to='posts/images', null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class CommentForPhoto(models.Model):
    comment = models.TextField(null=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    photo_id = models.ForeignKey(Photo, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class PhotoLike(models.Model):
    user_id = models.ForeignKey(User, models.CASCADE)
    photo_id = models.ForeignKey(Photo, models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Reel(models.Model):
    description = models.TextField()
    video = models.FileField(upload_to="posts/videos", null=True)
    user_id = models.ForeignKey(User, models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class CommentForReel(models.Model):
    comment = models.TextField()
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    reel_id = models.ForeignKey(Reel, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class ReelLike(models.Model):
    user_id = models.ForeignKey(User, models.CASCADE)
    reel_id = models.ForeignKey(Reel, models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class UserFollowing(models.Model):
    user_followed = models.ForeignKey(User, related_name="followers", on_delete=models.CASCADE,
                                      null=True)
    user_following = models.ForeignKey(User, related_name="following", on_delete=models.CASCADE,
                                       null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Message(models.Model):
    message = models.TextField()
    user_sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="sender", on_delete=models.CASCADE)
    user_receiver = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="receiver", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

kinect_core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Photo, Reel


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=200, required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email address is already in use.")
        return email


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['description', 'photo_path']


class ReelForm(forms.ModelForm):
    class Meta:
        model = Reel
        fields = ['description', 'video']


class SearchForm(forms.Form):
    query = forms.CharField(max_length=100, label='Search other users')


class LoginForm(forms.Form):
    username = forms.CharField(max_length=200)
    password = forms.CharField(widget=forms.PasswordInput())

kinect_core/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages
from .forms import SignUpForm, PhotoForm, ReelForm, SearchForm, LoginForm
from django.contrib.auth.decorators import login_required
from .models import UserFollowing, PhotoLike, Photo
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.urls import reverse
from django.views.decorators.http import require_POST

User = get_user_model()


# Create your views here.

def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "Login Succesfully")
                return redirect('home')
            else:
                # Check if the username exists
                if User.objects.filter(username=username).exists():
                    # If username exists, password is likely incorrect
                    form.add_error('password', "Incorrect password. Please try again.")
                else:
                    # Username does not exist
                    form.add_error('username', "Username does not exist.")
    else:
        form = LoginForm()

    return render(request, 'kinect_core/login.html', {
        'form': form
    })


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            user = authenticate(username=email, password=password)
            messages.success(request, "Account created successfully")
            return redirect('login')
    else:
        form = SignUpForm()
    return render(request, 'kinect_core/signup.html', {
        'form': form
    })


@login_required
def home(request):
    if request.method == 'POST':
        photo_form = PhotoForm(request.POST, request.FILES)
        if photo_form.is_valid():
            photo = photo_form.save(commit=False)
            photo.user = request.user
            photo.save()
            messages.success(request, 'Photo posted successfully.')
            return redirect('home')  # Redirect to the same page to refresh the view
        else:
            messages.error(request, 'Error posting photo. Please check the form.')
    else:
        photo_form = PhotoForm()

    followed_users = UserFollowing.objects.filter(user_following=request.user).values_list('user_followed', flat=True)
    photos_from_following = Photo.objects.filter(user__in=followed_users).order_by('-created_at')
    own_photos = Photo.objects.filter(user=request.user)
    photos = (photos_from_following | own_photos).order_by('-created_at')



    context = {
        'photos': photos,
        'photo_form': photo_form
    }

    return render(request, 'kinect_core/home.html', context)


@login_required
def createPhoto(request):
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            photo = form.save(commit=False)
            photo.user = request.user
            photo.save()

            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'success': True, 'message': 'Photo posted successfully'})

            messages.success(request, 'Photo posted successfully.')
            return redirect('home')

        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'success': False, 'message': 'Error posting photo. Please check the form.'})

    return redirect('home')


@login_required
def profile_view(request, user_id):
    user = get_object_or_404(User, id=user_id)
    followers = user.followers.count()
    following = user.following.count()
    photos = Photo.objects.filter(user=user)
    is_following = UserFollowing.objects.filter(user_following=request.user, user_followed=user).exists()
    return render(request, 'kinect_core/profile.html', {
        'photos': photos,
        'user': user,
        'followers': followers,
        'following': following,
        'is_following': is_following,
    })


@login_required
def follow_user(request, user_id):
    user_to_follow = get_object_or_404(User, id=user_id)
    if user_to_follow != request.user:
        UserFollowing.objects.get_or_create(user_following=request.user, user_followed=user_to_follow)
    return redirect('profile', user_id=user_id)


@login_required
def unfollow_user(request, user_id):
    user_to_unfollow = get_object_or_404(User, id=user_id)
    if request.user != user_to_unfollow:
        follow_object = UserFollowing.objects.filter(user_following=request.user, user_followed=user_to_unfollow)
        follow_object.delete()
    return redirect('profile', user_id=user_id)


def search(request):
    query = request.GET.get('query', '')
    results = []

    print(f"Received query: {query}")  # Debugging: Print the received query

    if query:
        results = User.objects.filter(
            username__icontains=query
        ) | User.objects.filter(
            first_name__icontains=query
        ) | User.objects.filter(
            last_name__icontains=query
        ) | User.objects.filter(
            email__icontains=query
        )

        print(f"Found {results.count()} results")  # Debugging: Print the number of results

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        print("Processing AJAX request...")  # Debugging: Confirm AJAX request

        results_data = []
        for user in results:
            print(f"Processing user: {user.first_name} {user.last_name}")  # Debugging: Print each user processed

            user_data = {
                'id': user.id,
                'first_name': user.first_name,
                'last_name': user.last_name,
                'profile_url': reverse('profile', args=[user.id])
            }
            results_data.append(user_data)

        print(
            f"Returning {len(results_data)} results in JSON")  # Debugging: Confirm the number of results being returned
        return JsonResponse({'results': results_data})

    print("Rendering search template")  # Debugging: Confirm template rendering
    return render(request, 'kinect_core/search.html', {
        'query': query,
        'results': results,
        'form': SearchForm(initial={'query': query}),
    })


def logout_user(request):
    logout(request)
    return redirect('login')

kinect_core/templates/kinect_core/create.html
<!-- create.html -->
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <!-- Display form errors if any -->
    {% if form.errors %}
        <div class="alert alert-danger">
            <strong>Error!</strong> Please correct the errors below.
        </div>
    {% endif %}
    
    <!-- Display each form field -->
    <div class="form-group">
        <label for="id_description">Description:</label>
        {{ form.description }}
        <!-- Display errors for description field if any -->
        {% for error in form.description.errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
    </div>
    
    <div class="form-group">
        <label for="id_photo_path">Photo:</label>
        {{ form.photo_path }}
        <!-- Display errors for photo_path field if any -->
        {% for error in form.photo_path.errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

kinect_core/templates/kinect_core/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home Page</title>
    <link rel="stylesheet" href="{% static 'kinect_core/css/home.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <style>
            body {
                background-color: black;
                color: white;
                margin: 0;
                padding: 0;
            }

            .container {
                background-color: black;
                display: flex;
                flex-direction: column;
                align-items: flex-start;
                justify-content: flex-start;
                position: fixed;
                left: 0;
                top: 0;
                width: 300px;
                height: 100vh;
                overflow-y: auto;
                box-shadow: 1px 0 0 white;
                padding: 20px;
            }

            .nav-item {
                display: flex;
                align-items: center;
                margin-bottom: 40px;
                transition: background-color 0.3s ease;
                color: inherit;
                text-decoration: none;
            }

            .nav-item i {
                margin-right: 20px;
            }

            .bottom-icon {
                margin-top: auto;
                cursor: pointer;
            }

            .post-card {
                background-color: white;
                border: 1px solid #dbdbdb;
                border-radius: 3px;
                max-width: 450px;
                margin: 20px auto;
                box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
                color: black;
            }

            .post-header {
                display: flex;
                align-items: center;
                padding: 15px;
            }

            .username {
                font-weight: bold;
            }

            .post-image img {
                width: 100%;
                height: 400px;
                object-fit: cover;
            }

            .post-description {
                padding: 15px;
            }

            .post-description p {
                margin: 0;
            }

            .icons i {
                margin: 5px;
            }

            .nav-item a:hover {
                background-color: #505050;
                text-decoration: none;
            }

            .nav-item a .icon {
                margin-right: 5px;
            }

            a {
                text-decoration: none;
                color: white;
            }

            .modal-body {
                color: black;
            }

            .btn.btn-primary {
                background-color: grey;
                color: white;
            }

            .nav-item .create-post {
                display: flex;
                align-items: center;
                cursor: pointer;
                color: inherit;
                text-decoration: none;
                text-decoration: none;
            }

            .nav-item .create-post i {
                margin-right: 15px;
                pointer: cursor;
            }

            .nav-item i:hover{
                background-color: #505050;
                text-decoration: none;
            }



    </style>
</head>
<body>
<div class="container">
    <div class="nav-item">
        <i class="fa fa-home"></i>
        <span>Home</span>
    </div>
    <div class="nav-item">
        <a href="{% url 'search' %}">
            <i class="fa fa-search"></i>
            <span>Search</span>
        </a>
    </div>
    <div class="nav-item">
        <i class="fa fa-compass"></i>
        <span>Explore</span>
    </div>
    <div class="nav-item">
        <i class="fa fa-play-circle"></i>
        <span>Reels</span>
    </div>
    <div class="nav-item">
        <i class="fa fa-paper-plane"></i>
        <span>Messages</span>
    </div>
    <div class="nav-item">
        <i class="fa fa-heart"></i>
        <span>Notifications</span>
    </div>

    <!-- Create Post Button -->
    <div class="nav-item create-post" data-bs-toggle="modal" data-bs-target="#createPostModal">
        <i class="fa fa-plus-square"></i>
        <span>Create Post</span>
    </div>


    <div class="nav-item">
        <a href="{% url 'profile' user.id %}">
            <i class="fa fa-user"></i>
            <span>Profile</span>
        </a>
    </div>
    <div class="bottom-icon" data-bs-toggle="modal" data-bs-target="#logoutModal">
        <span>Logout</span>
    </div>
</div>

{% for photo in photos %}
<div class="post-card">
    <div class="post-header">
        <img src="" alt="Profile Picture">
        <span class="username">{{ photo.user.username }}</span>
    </div>

    <div class="post-image">
        <img src="{{ photo.photo_path.url }}" alt="{{ photo.description }}">
    </div>

    <div class="icons">
        <i class="fa fa-heart"></i>
        <i class="fa fa-comment"></i>
        <i class="fa fa-paper-plane"></i>
    </div>

    <div class="post-description">
        <p><strong>{{ photo.user.username }} </strong>{{ photo.description }}</p>
    </div>
</div>
{% endfor %}

<!-- Create Post Modal -->
<div class="modal fade" id="createPostModal" tabindex="-1" aria-labelledby="createPostModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createPostModalLabel">Create a New Post</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="createPostForm" method="POST" enctype="multipart/form-data" action="{% url 'create' %}">
                    {% csrf_token %}
                    {{ photo_form.as_p }}
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Post</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Logout Modal -->
<div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="logoutModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="logoutModalLabel">Logout</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to logout?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <a href="{% url 'logout' %}" class="btn btn-danger" id="logout">Logout</a>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>




</body>
</html>

kinect_core/templates/kinect_core/login.html
{% load static %}
{% load widget_tweaks %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'kinect_core/css/login.css'%}">
</head>
<body>

<div class="container">
    <form method="POST">
        {% csrf_token %}
        <img src="{% static 'kinect_core/images/kinect.png'%}" alt="img.jpg">

        <!-- Display non-field errors -->
        {% if form.non_field_errors %}
            <div class="alert alert-danger">
                {% for error in form.non_field_errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}

        <div class="form-group">
            {% render_field form.username class="form-control" placeholder="Username" %}
            {% if form.username.errors %}
                <div class="text-danger">
                    {% for error in form.username.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            {% render_field form.password class="form-control" placeholder="Password" %}
            {% if form.password.errors %}
                <div class="text-danger">
                    {% for error in form.password.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <button class="btn btn-primary" type="submit">Login</button>
    </form>

    <div class="signup-link">
        <p>Don't have an account? <a href="{% url 'signup' %}">Sign Up</a></p>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

kinect_core/templates/kinect_core/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ profile_user.username }}'s Profile</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <style>

      body{
        background-color: black;
        color: white;
      }
        .profile-header {
            display: flex;
            align-items: center;
            padding: 20px;
        }
        .profile-picture {
            border-radius: 50%;
            width: 150px;
            height: 150px;
            margin-right: 20px;
        }
        .profile-info {
            flex-grow: 1;
        }
        .profile-info h1 {
            margin: 0;
        }
        .nav-tabs {
            margin-top: 20px;
        }
        .tab-content {
            margin-top: 20px;
        }
        .photos .photo,
        .reels .reel {
            position: relative;
            overflow: hidden;
            margin-bottom: 15px;
        }
        .photos .photo img,
        .reels .reel video {
            width: 100%;
            height: auto;
            display: block;
        }
        .reels .reel {
            width: 100%;
        }
        .post-card {
        background-color: white;
        border: 1px solid #dbdbdb;
        border-radius: 3px;
        max-width: 450px;
        margin: 20px auto;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        color: black;
      }

      .post-header {
        display: flex;
        align-items: center;
        padding: 15px;
      }
      .post-image img {
        width: 100%;
        height: 400px;
        object-fit: cover;
      }

      .post-description {
        padding: 15px;
      }

      .post-description p {
        margin: 0;
      }

      .icons i {
        margin: 5px;
      }


    </style>
</head>
<body>
<div class="container">
    <div class="profile-header">
        <img src="{% static 'images/default-avatar.png' %}" alt="Profile Picture" class="profile-picture">
        <div class="profile-info">
            <h1>{{ profile_user.username }}</h1>
            <p>{{ profile_user.email }}</p>
            <p>Followers: {{ followers }} • Following: {{ following }}</p>
            {% if is_following %}
            <a href="{% url 'unfollow' user.id %}" class="btn btn-danger">Unfollow</a>
            {% else %}
            <a href="{% url 'follow' user.id %}" class="btn btn-primary">Follow</a>
            {% endif %}
        </div>
    </div>

    <ul class="nav nav-tabs" id="profileTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="photos-tab" data-toggle="tab" href="#photos" role="tab"
               aria-controls="photos" aria-selected="true">Photos</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="reels-tab" data-toggle="tab" href="#reels" role="tab" aria-controls="reels"
               aria-selected="false">Reels</a>
        </li>
    </ul>

    {% for photo in photos %}
    <div class="post-card">
        <div class="post-header">
            <img src="" alt="Profile Picture">
            <span class="username">{{ photo.user.username }}</span>
        </div>

        <div class="post-image">
            <img src="{{ photo.photo_path.url }}" alt="{{ photo.description }}">
        </div>

        <div class="icons">
            <i class="fa fa-heart"></i>
            <i class="fa fa-comment"></i>
            <i class="fa fa-paper-plane"></i>
        </div>


        <div class="post-description">
            <p><strong>{{ photo.user.username }} </strong>{{ photo.description }}</p>
        </div>
    </div>
    {% endfor %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>

</div>


</body>
</html>

kinect_core/templates/kinect_core/search.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search Users</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        body {
            background-color: black;
            color: white;
        }
        .search-form {
            margin-top: 20px;
        }
        .search-results {
            margin-top: 20px;
        }
        .search-results .user {
            padding: 10px;
            border-bottom: 1px solid #ccc;
        }

        .form-control{
            margin-bottom: 10px;
            width: 500px;
        }



    </style>
</head>
<body>
<div class="container">
    <h1>Search for Users</h1>

    <form method="GET" action="{% url 'search' %}" class="search-form" id="searchForm">
        {% render_field form.query placeholder="Search" class+="form-control" id="query_field"%}
        <hr>
        <button type="submit" class="btn btn-primary">Search</button>
    </form>

    <div class="search-results" id="searchResults">
        <!--Display results here -->

    </div>
    <a href="{% url 'home' %}" class="btn btn-secondary mt-3">Home</a>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function(){

       $('#searchForm').on('submit', function(e){
            e.preventDefault(); // Prevent default from submission

            let query = $('input[name="query"]').val(); // Get the value of input field

            $.ajax({
                url : $(this).attr('action'),
                type : 'GET',
                data: {'query': query},
                dataType: 'json',
               success: function(response) {
               console.log('AJAX response:', response); // Log the entire response object to see its structure

               let resultsContainer = $('#searchResults');
               resultsContainer.empty();  // Clear previous results

                if (response.results.length > 0) {
                let resultsHtml = '<h2>Search Results for "' + query + '":</h2><ul class="list-group">';
                response.results.forEach(function(user) {
                    resultsHtml += '<li class="list-group-item user">' +
                                   '<a href="' + user.profile_url + '">' +
                                   user.first_name + ' ' + user.last_name +
                                   '</a></li>';
                });
                resultsHtml += '</ul>';
                resultsContainer.html(resultsHtml);
            } else {
                resultsContainer.html('<p>No users found.</p>');
                }
            },
             error: function(){
                    alert("An occurred while searching. Please try again...");
                }
            });
       });
});


</script>

</body>
</html>